# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "x10sdv-tln4f"
BBFILE_PATTERN_x10sdv-tln4f = ""

BBFILE_PRIORITY_x10sdv-tln4f = "5"
LAYERSERIES_COMPAT_x10sdv-tln4f = "wrynose whinlatter"

